/**
 * Geek Budget - OpenAPI 3.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: ilya.korolev@outlook.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BankAccountInfo } from './bankAccountInfo';


export interface AccountNoID { 
    name: string;
    description?: string;
    type: AccountNoID.TypeEnum;
    bankInfo?: BankAccountInfo;
}
export namespace AccountNoID {
    export type TypeEnum = 'expense' | 'income' | 'asset';
    export const TypeEnum = {
        Expense: 'expense' as TypeEnum,
        Income: 'income' as TypeEnum,
        Asset: 'asset' as TypeEnum
    };
}


