/**
 * Geek Budget - OpenAPI 3.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: ilya.korolev@outlook.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CurrencyAggregation } from './currencyAggregation';


export interface Aggregation { 
    from: string;
    to: string;
    granularity: Aggregation.GranularityEnum;
    intervals: Array<string>;
    currencies: Array<CurrencyAggregation>;
}
export namespace Aggregation {
    export type GranularityEnum = 'month' | 'year';
    export const GranularityEnum = {
        Month: 'month' as GranularityEnum,
        Year: 'year' as GranularityEnum
    };
}


