/**
 * Geek Budget - OpenAPI 3.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: ilya.korolev@outlook.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BankAccountInfoBalancesInner } from './bankAccountInfoBalancesInner';


export interface BankAccountInfo { 
    accountId?: string;
    bankId?: string;
    /**
     * List of balances for this account. It\'s an array since one account could hold multiple currencies, for example, cash account could hold EUR, USD and CZK. Or one bank account could hold multiple currencies.
     */
    balances?: Array<BankAccountInfoBalancesInner>;
}

