/**
 * Geek Budget - OpenAPI 3.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: ilya.korolev@outlook.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Movement } from './movement';


export interface MatcherNoID { 
    name: string;
    outputDescription?: string;
    amount?: number;
    currencyRegExp?: string;
    partnerNameRegExp?: string;
    partnerAccountNumber?: string;
    descriptionRegExp?: string;
    extraRegExp?: string;
    outputMovements?: Array<Movement>;
}

