/**
 * Geek Budget - OpenAPI 3.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: ilya.korolev@outlook.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Notification { 
    id: string;
    date: string;
    type: Notification.TypeEnum;
    url?: string;
    title: string;
    description: string;
}
export namespace Notification {
    export type TypeEnum = 'other' | 'balanceMatch' | 'balanceDoesntMatch';
    export const TypeEnum = {
        Other: 'other' as TypeEnum,
        BalanceMatch: 'balanceMatch' as TypeEnum,
        BalanceDoesntMatch: 'balanceDoesntMatch' as TypeEnum
    };
}


