/**
 * Geek Budget - OpenAPI 3.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: ilya.korolev@outlook.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Account } from './account';
import { User } from './user';
import { BankImporter } from './bankImporter';
import { Transaction } from './transaction';
import { Matcher } from './matcher';
import { Currency } from './currency';


export interface WholeUserData { 
    user?: User;
    currencies?: Array<Currency>;
    accounts?: Array<Account>;
    transactions?: Array<Transaction>;
    matchers?: Array<Matcher>;
    bankImporters?: Array<BankImporter>;
}

